pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -f /RocketMaven/pom.xml -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                dir('RocketMaven') {
                    sh 'mvn clean test -Dmaven.test.failure.ignore=true'
                    }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}